keys:
  # Clients
  - &compy age1sfml49j8htm9cgzzewm4nkglkq2klfx4ljrsp4z2dyn3yeqk6d8qv3n0ag
  # Servers
  - &publy age1dnkzhchnf3zj48msg08hqxmcf0az3csffcg4jjm9s8r7x2c303ysr0tfzg
creation_rules:
  # Publy secrets
  - path_regex: secrets/publy\.yaml$
    key_groups:
      - age:
        - *compy
        - *publy
