keys:
  # Clients
  - &compy age1sfml49j8htm9cgzzewm4nkglkq2klfx4ljrsp4z2dyn3yeqk6d8qv3n0ag
  - &framy age1atk0ad8gv9eeuz0nn5z8798plqqkjue870aa7k8f0y0nrdauuc4qc5wsaj
  # Servers
  - &publy age1dnkzhchnf3zj48msg08hqxmcf0az3csffcg4jjm9s8r7x2c303ysr0tfzg
  - &servy age1waz6xepvnrsp4fmstqnfnmvr6g5h6lnwl4qlzava848hl38j8dzqwe9g3v
creation_rules:
  # --- Groups ---
  # Home secrets
  - path_regex: secrets/home\.yaml$
    key_groups:
      - age:
        - *compy
        - *framy
        - *servy
  # --- Servers ---
  # Publy secrets
  - path_regex: secrets/publy\.yaml$
    key_groups:
      - age:
        - *compy
        - *framy
        - *publy
  # Servy secrets
  - path_regex: secrets/servy\.yaml$
    key_groups:
      - age:
        - *compy
        - *framy
        - *servy
